# Generated by Django 4.0 on 2024-01-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physician',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
